### ISSUE TITLE
Is there any way to get dimensions from images pulled from a docx file?

### ISSUE THREAD

**Issue by otaviogaiao** [ShayHill/docx2python#10]
Hello! First of all, thanks for the amazing lib. Its being really helpful for the project I'm working on. 

I was going through the docs, and I haven't found a way to get the dimensions of the images contained in a docx file. Is this possible? If so, can you point me in the right direction please?

Thanks.

**Comment by ShayHill** [comment]
That feature is not included at the moment, but I'll have a look to see if I can include it (without adding Pillow as a dependency).

Would have to be another attribute of the output. A dictionary maybe.

________________________________

**Comment by otaviogaiao** [comment]
Oh I see. Thanks!!!

**Comment by ShayHill** [comment]
# here's a little script to give you the image sizes (if you install Pillow)

```
from PIL import Image
import os

image_dir = r"wherever\you\exported\the\images"

for image_name in os.listdir(image_dir):
    image_file = Image.open(os.path.join(image_dir, image_name))
    print(f'{image_name}, {image_file.size}')
```
