### ISSUE TITLE
KeyError exception when processing document; image with no r:id attribute.

### ISSUE THREAD

**Issue by forky2** [ShayHill/docx2python#13]
I've managed to get an exception processing a document. (Happy to provide the document.) As per my subject, there's an imagedata element with no r:id attribute.

The offending element:
`<v:imagedata croptop="-65520f" cropbottom="65520f"/>`

The exception.
```
Traceback (most recent call last):
  File "./process.py", line 99, in <module>
    process_zip("Specs/2020-06/Rel-16/25_series/25101-g10.zip")
  File "./process.py", line 70, in process_zip
    doc_data = docx2python(docx_file)
  File "/home/forky2/projects/docx2python/docx2python/main.py", line 61, in docx2python
    body = file_text(context["officeDocument"])
  File "/home/forky2/projects/docx2python/docx2python/main.py", line 56, in file_text
    return get_text(unzipped, context)
  File "/home/forky2/projects/docx2python/docx2python/docx_text.py", line 264, in get_text
    branches(ElementTree.fromstring(xml))
  File "/home/forky2/projects/docx2python/docx2python/docx_text.py", line 248, in branches
    branches(child)
  File "/home/forky2/projects/docx2python/docx2python/docx_text.py", line 248, in branches
    branches(child)
  File "/home/forky2/projects/docx2python/docx2python/docx_text.py", line 248, in branches
    branches(child)
  [Previous line repeated 2 more times]
  File "/home/forky2/projects/docx2python/docx2python/docx_text.py", line 239, in branches
    rId = child.attrib[qn("r:id")]
KeyError: '{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id'
```

In my project I'm going to modify to gracefully skip over the KeyError. Would you want me to raise a PR to absorb my fix? (I'm not sure whether the document is invalid or not; there's a lot of vector graphics in it, and I don't know the docx schema well enough.

**Comment by ShayHill** [comment]
Thank you for identifying this. I’d like to have a look at the document, please.

**Comment by forky2** [comment]
Sure thing! [25101-g10.docx](https://github.com/ShayHill/docx2python/files/5511285/25101-g10.docx)

**Comment by ShayHill** [comment]
---- version 1.27.1 - 201115 Continue when image r:id is not found

A user found a docx `imagedata` element with a missing `r:id` element. The `r:id` number gives the location of an image
filename. I presume this `imagedata` element is a vector graphic, which `docx2python` does not and will not support.
This makes two out of three `r:id` lookup positions (`hyperlink`, `image`, and `imagedata`) for which users have found
absent `r:id`. None so far have contained anything meaningful for text export (internal links in a previous case and
vector graphics in this case). Now all `r:id` lookups take place within `suppress(KeyId)` context.

This will only happen where the program would previously have failed with a KeyError, so no previous behavior (which
allowed the program to complete) has been altered.

Thank you forky2. If you're having success with docx2python, please star the project.
