### ISSUE TITLE
Soft line breaks are not processed

### ISSUE THREAD

**Issue by slarionoff** [ShayHill/docx2python#16]
Looks like the soft line breaks (when you press Shift+Enter) are just being removed and strings with them are returned as concatenated. I think those can be treated the same way as usual line breaks.

**Comment by ShayHill** [comment]
Thank you for the report. Can you send an example docx?

Sent from my iPhone

On May 25, 2021, at 8:23 AM, slarionoff ***@***.***> wrote:

﻿

Looks like the soft line breaks (when you press Shift+Enter) are just being removed and strings are shown as concatenated. I think those can be treated the same way as usual line breaks.

**Comment by slarionoff** [comment]
Yes, sure, please find in an attachement.
[lib issue.docx](https://github.com/ShayHill/docx2python/files/6540927/lib.issue.docx)
[issue analysis.py.txt](https://github.com/ShayHill/docx2python/files/6540937/issue.analysis.py.txt)

Results:

[['Line1Line2Line3', 'Line4', '']]
[['']]

Process finished with exit code 0


Expected results (I guess):

[['Line1', 'Line2', 'Line3', 'Line4', '']]
[['']]

**Comment by ShayHill** [comment]
Thank you. Will have a look.

Sent from my iPhone

On May 25, 2021, at 11:40 AM, slarionoff ***@***.***> wrote:

﻿

Yes, sure, please find in an attachement.
lib issue.docx<https://github.com/ShayHill/docx2python/files/6540927/lib.issue.docx>
issue analysis.py.txt<https://github.com/ShayHill/docx2python/files/6540937/issue.analysis.py.txt>

Results:

[['Line1Line2Line3', 'Line4', '']]
[['']]

Process finished with exit code 0

Expected results (I guess):

[['Line1', 'Line2', 'Line3', 'Line4', '']]
[['']]

**Comment by ShayHill** [comment]
> 
> 
> Yes, sure, please find in an attachement.
> [lib issue.docx](https://github.com/ShayHill/docx2python/files/6540927/lib.issue.docx)
> [issue analysis.py.txt](https://github.com/ShayHill/docx2python/files/6540937/issue.analysis.py.txt)
> 
> Results:
> 
> [['Line1Line2Line3', 'Line4', '']]
> [['']]
> 
> Process finished with exit code 0
> 
> Expected results (I guess):
> 
> [['Line1', 'Line2', 'Line3', 'Line4', '']]
> [['']]

Docx2Python v2 output is now `[[[['Line1\nLine2\nLine3', 'Line4', '']], [['']]], [[['']]]]`.

A `\n` has been inserted at each soft break.

Treating soft breaks exactly as hard breaks would start a new paragraph at each hard break. This would cause problems if a user had soft breaks inside a heading.

The requested behavior, soft breaks exactly as hard breaks, can be accomplished with

`from docx2python import docx2python
from docx2python.iterators import iter_cells

body = docx2python('lib issue.docx').body
for cell in iter_cells(body):
    cell[:] = sum((x.split('\n') for x in cell), start=[])
# body = [[[['Line1', 'Line2', 'Line3', 'Line4', '']], [['']]], [[['']]]]`

Thank you for identifying this issue.

**Comment by ShayHill** [comment]
Closing. Behavior updated in Docx2Python v2.
