### ISSUE TITLE
syntax error when running sample code

### ISSUE THREAD

**Issue by stefan-hock20** [ShayHill/docx2python#2]
when running the following snippet from the sampel code

from docx2python import docx2python

# extract docx content
docx2python('E:/nlp/author_it/docuvera/IT5562S_CCDS 0281-09_clean.docx')

the following error is thrown:

Traceback (most recent call last):
  File "E:/.../tests/test_wod_images.py", line 1, in <module>
    from docx2python import docx2python
  File "C:\...\Python\Python35\lib\site-packages\docx2python\__init__.py", line 1, in <module>
    from .main import docx2python
  File "C:\...\Python\Python35\lib\site-packages\docx2python\main.py", line 14, in <module>
    from docx2python.docx_output import DocxContent
  File "C:\...\Python\Python35\lib\site-packages\docx2python\docx_output.py", line 27
    ) -> None:
    ^
SyntaxError: invalid syntax

Any hints?

**Comment by ShayHill** [comment]
Thank you for the report. What is your python version? And will you please send IT5562S_CCDS 0281-09_clean.docx?

-Shay

**Comment by stefan-hock20** [comment]
I found the problem
 
in file
...\Python\Python35\lib\site-packages\docx2python\docx_output.py

class DocxContent:
    """Holds return values for docx content."""
    def __init__(
        self,
        *,
        header: TablesList,
        footer: TablesList,
        body: TablesList,
        footnotes: TablesList,
        endnotes: TablesList,
        properties: Dict[str, Any],
        images: Dict[str, bytes],    --->>>>>>>>>>>>>>>>>> CHANGED THIS TO >> images: Dict[str, bytes]  >> removed comma
    ) -> None:
        self.header = header
        self.footer = footer
        self.body = body
        self.footnotes = footnotes
        self.endnotes = endnotes
        self.properties = properties
        self.images = images
    @property
    def document(self) -> TablesList:
        """All docx "tables" concatenated."""
        return self.header + self.body + self.footer + self.footnotes + self.endnotes
    @property
    def text(self) -> str:
        """All docx paragraphs, "\n\n" delimited."""
        return "\n\n".join(iter_at_depth(self.document, 4))
    @property
    def html_map(self) -> str:
        """A visual mapping of docx content."""
        return get_html_map(self.document)
---

**Comment by stefan-hock20** [comment]
Hi Shay
 
I found the problem
 
in file
...\Python\Python35\lib\site-packages\docx2python\docx_output.py
 

class DocxContent:    """Holds return values for docx content."""
    def __init__(        self,        *,        header: TablesList,        footer: TablesList,        body: TablesList,        footnotes: TablesList,        endnotes: TablesList,        properties: Dict[str, Any],        images: Dict[str, bytes],    --->>>>>>>>>>>>>>>>>> CHANGED THIS TO >> images: Dict[str, bytes]  >> removed comma    ) -> None:        self.header = header        self.footer = footer        self.body = body        self.footnotes = footnotes        self.endnotes = endnotes        self.properties = properties        self.images = images
    @property    def document(self) -> TablesList:        """All docx "tables" concatenated."""        return self.header + self.body + self.footer + self.footnotes + self.endnotes
    @property    def text(self) -> str:        """All docx paragraphs, "\n\n" delimited."""        return "\n\n".join(iter_at_depth(self.document, 4))
    @property    def html_map(self) -> str:        """A visual mapping of docx content."""        return get_html_map(self.document)


---
Ich habe diese Nachricht mit der WEB.DE Mail App für Windows erstellt.


-----Ursprüngliche Nachricht-----Von: "Shay Hill" <notifications@github.com>Gesendet: Dienstag, 14. Januar 2020 13:14An: ShayHill/docx2python <docx2python@noreply.github.com>Cc: stefan-hock20 <stefan.hock@web.de>; Author <author@noreply.github.com>Betreff: Re: [ShayHill/docx2python] syntax error when running sample code (#2)</author@noreply.github.com></stefan.hock@web.de></docx2python@noreply.github.com>

**Comment by stefan-hock20** [comment]
Hi Shay 
my document.xml file codes images in the follwowing way:
<w:pict>
	<v:shape id=Figure 1" o:spid="_x0000_i1085" type="#_x0000_t75" style="width:441.6pt;height:264.6pt;visibility:visible"><v:imagedata r:id="rId50" o:title=""/></v:shape>
</w:pict>
Looks like this is not captured in your implmenetatiion?
Any hint on how to incorporate this?

**Comment by ShayHill** [comment]
Thank you. That's pretty huge!

Iirc,

1. Such trailing commas are allowed in Python 3.6+ but not before.

2. My editor is configured to flag incompatibilities for 3.4+.

If I'm right about both of those, the editor missed it, and I need to submit a bug report.

Either way, I'll find and remove these manually and test explicitly with 3.4+. Thank you again.

Sent via the Samsung Galaxy S9+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ShayHill** [comment]
I'd like to incorporate that functionality into my package. Can you send an example file?

Sent via the Samsung Galaxy S9+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by stefan-hock20** [comment]
here it is
[test-figure-2.docx](https://github.com/ShayHill/docx2python/files/4059828/test-figure-2.docx)

**Comment by ShayHill** [comment]
Excellent. Thank you.

**Comment by ShayHill** [comment]
I have updated the package to handle files like yours. All I need is your permission to include your file, test-figure-2.docx, in the test cases. Is this alright with you? I cannot create a file like yours with my version of Word.

-Shay

**Comment by ShayHill** [comment]
Updated. Trailing commas removed to allow 3.4 and 3.5 compatibility. Will now capture and mark images in <pict> elements.

**Comment by stefan-hock20** [comment]
Hi Shay
 
 
can you resend the word file I provided?
Need to double check if the customer and/or product is removed from the figure
 
regards
Stefan

---
Ich habe diese Nachricht mit der WEB.DE Mail App für Windows erstellt.


-----Ursprüngliche Nachricht-----Von: "Shay Hill" <notifications@github.com>Gesendet: Montag, 3. Februar 2020 12:55An: ShayHill/docx2python <docx2python@noreply.github.com>Cc: stefan-hock20 <stefan.hock@web.de>; Author <author@noreply.github.com>Betreff: Re: [ShayHill/docx2python] syntax error when running sample code (#2)</author@noreply.github.com></stefan.hock@web.de></docx2python@noreply.github.com>


Closed #2.

**Comment by ShayHill** [comment]
Here it is.

**Comment by stefan-hock20** [comment]
no files attached

---
Ich habe diese Nachricht mit der WEB.DE Mail App für Windows erstellt.


-----Ursprüngliche Nachricht-----Von: "Shay Hill" <notifications@github.com>Gesendet: Montag, 3. Februar 2020 14:14An: ShayHill/docx2python <docx2python@noreply.github.com>Cc: stefan-hock20 <stefan.hock@web.de>; Author <author@noreply.github.com>Betreff: Re: [ShayHill/docx2python] syntax error when running sample code (#2)</author@noreply.github.com></stefan.hock@web.de></docx2python@noreply.github.com>

**Comment by ShayHill** [comment]
How about now? If this doesn’t work, I’ll log into github and try something from there.

**Comment by stefan-hock20** [comment]
no

---
Ich habe diese Nachricht mit der WEB.DE Mail App für Windows erstellt.


-----Ursprüngliche Nachricht-----Von: "Shay Hill" <notifications@github.com>Gesendet: Montag, 3. Februar 2020 14:16An: ShayHill/docx2python <docx2python@noreply.github.com>Cc: stefan-hock20 <stefan.hock@web.de>; Author <author@noreply.github.com>Betreff: Re: [ShayHill/docx2python] syntax error when running sample code (#2)</author@noreply.github.com></stefan.hock@web.de></docx2python@noreply.github.com>

**Comment by ShayHill** [comment]
Hmmmm. Can you get it from here?

https://github.com/ShayHill/docx2python/issues/2#issuecomment-574220785

-Shay

**Comment by stefan-hock20** [comment]
that works
 
I am fine with the figure, please delete all text that is not needed from the document (e.g. header , confidentiallity info etc.)
 
 
 

---
Ich habe diese Nachricht mit der WEB.DE Mail App für Windows erstellt.


-----Ursprüngliche Nachricht-----Von: "Shay Hill" <notifications@github.com>Gesendet: Montag, 3. Februar 2020 14:20An: ShayHill/docx2python <docx2python@noreply.github.com>Cc: stefan-hock20 <stefan.hock@web.de>; Author <author@noreply.github.com>Betreff: Re: [ShayHill/docx2python] syntax error when running sample code (#2)</author@noreply.github.com></stefan.hock@web.de></docx2python@noreply.github.com>

**Comment by ShayHill** [comment]
Thank you.
