### ISSUE TITLE
ability to save/modify documents?

### ISSUE THREAD

**Issue by SleepyHIpster** [ShayHill/docx2python#20]
Not an issue but a feature request

I'm potentially just really bad at reading documentation but I've searched alot and haven't found a way to save any changes made to the document again. I was hoping for a .save() function similar to python-docx. If you know where I can find a way to save it i would love to know.

Not sure if this is possible but would add lots of functionality as it is the only i know that seems to handle text boxes well.

**Comment by ShayHill** [comment]
Apologies, I thought I'd responded to this one 12 days ago.

Docx2Python v2 will expose the docx xml to allow straightforward changes like search and replace. That's as far as I plan to go with saving. Project Python-Docx allows saving files, but the author has accomplished this by re-building large portions of the xml functionality in Python. I will not do this for Docx2Python, but I will add a function to save altered xml back into a readable .docx (if you know what you're doing). This will add a dependency (for zipping the file).

I should be able to get this into Docx2Python v2 in the next two weeks. The alpha version should work fine, but I'm waiting for a work project that will put it through a good test before official release. Thank you for your request.
