### ISSUE TITLE
Latex equation output incorrect when html=True

### ISSUE THREAD

**Issue by usr3** [ShayHill/docx2python#30]
When `<, >` is present inside equations, it's converted to html entities which is incorrect inside <latex> tags.

The file attached 
[equations.docx](https://github.com/ShayHill/docx2python/files/7790084/equations.docx)
gives the following output:
`[[[['Professional Format', '<latex>CO32-&lt;CO2&lt;CO</latex>', 'Linear Format', '<latex>CO_3^{\left(2-\right)}&lt;CO_2&lt;CO</latex>']]]]`

This is due to commit be6a7892bbd61750bbabb0391a234473af2a6eea in https://github.com/ShayHill/docx2python/blob/be6a7892bbd61750bbabb0391a234473af2a6eea/docx2python/docx_text.py#L152

**Comment by ShayHill** [comment]
Addressed. I'll have to take your word for it, because I'm not an expert on html. From my tests, it seems `&lt;` and `<` render the same in Edge and Firefox. Thank you.

    Professional Format<br>
    <code><latex>01x</latex></code><br>
    <latex>01x</latex><br><br>

    Linear Format<br>
    <code><latex>\\int_{0}^{1}x</latex></code><br>
    <latex>\\int_{0}^{1}x</latex><br><br>

    Linear Format with <code>&lt;</code><br>
    <code><latex>\\int0&lt;1x&lt;5</latex></code><br>
    <latex>\\int0&lt;1x&lt;5</latex><br><br>

    Linear Format with &lt;<br>
    <code><latex>\\int0<1x<5</latex></code><br>
    <latex>\\int0<1x<5</latex><br><br>

    Linear Format with <code>&lt;&gt;</code><br>
    <code><latex>\\int0&lt;&gt;1x&lt;&gt;5</latex></code><br>
    <latex>\\int0&lt;&gt;1x&lt;&gt;5</latex><br><br>

    Linear Format with &lt;&gt;<br>
    <code><latex>\\int0<>1x<>5</latex></code><br>
    <latex>\\int0<>1x<>5</latex><br><br>

    Linear Format with <code>&lt;1x&gt;</code><br>
    <code><latex>\\int0&lt;1x&gt;5</latex></code><br>
    <latex>\\int0&lt;1x&gt;5</latex><br><br>

    Linear Format with &lt;1x&gt;<br>
    <code><latex>\\int0<1x>5</latex></code><br>
    <latex>\\int0<1x>5</latex><br><br>

**Comment by usr3** [comment]
> Addressed. I'll have to take your word for it, because I'm not an expert on html. From my tests, it seems `&lt;` and `<` render the same in Edge and Firefox. Thank you.

Thanks. Yes you're correct, `&lt;` will render as `<` in the browser as it is a valid html entity. It's just that being inside the latex breaks it from being parsed by libraries such
as [mathjax](https://github.com/mathjax/MathJax).

**Comment by ShayHill** [comment]
Good to know. Thank you.
