### ISSUE TITLE
[Feature Request] Option to split and duplicate merged cells

### ISSUE THREAD

**Issue by dshefman1** [ShayHill/docx2python#32]
#### Background: 
Currently, the following, example table below cannot be recreated from the docx2python table output without information from the original, docx table because the docx2python table output is a [jagged array](https://en.wikipedia.org/wiki/Jagged_array#:~:text=In%20computer%20science%2C%20a%20jagged,edges%20when%20visualized%20as%20output.) of 3 nested arrays of length [3, 4, 4]. This is the result of horizontal merging of cells 2 and 3 of row 0.

| row0cell1 | row0cell2&3 | row0cell4 |
| -----------| ----------- | --------------|
| row1cell1 | row1cell2 \| row1cell3 | row1cell4 |
| row2cell1 | row2cell2 \| row2cell3 | row2cell4 |

Currently, the docx2python table output would be the following jagged array with 3 nested arrays of length [3, 4, 4]. As a result, if this nested array is turned back into a table, the columns will not line up as they did in the original docx table:
`[`
`[['row0cell1'], ['row0cell2&3'], ['row0cell4']],`
`[['row1cell1'], ['row1cell2'], ['row1cell3'], ['row1cell4']], `
`[['row2cell1'], ['row2cell2'], ['row2cell3'], ['row2cell4']]`
`]`

#### Feature Request: 
A new parameter named `duplicate_merged_cells`. When this parameter is set to `True` the table output from docx2python will be a rectangular array with 3 nested arrays of length [4, 4, 4]. If this nested array is turned back into a table, the columns line up as they did in the original docx table, and the cells can be merged again if desired.
`[`
`[['row0cell1'], ['row0cell2&3'], ['row0cell2&3'], ['row0cell4']],`
`[['row1cell1'], ['row1cell2'], ['row1cell3'], ['row1cell4']], `
`[['row2cell1'], ['row2cell2'], ['row2cell3'], ['row2cell4']]`
`]`

**Comment by ShayHill** [comment]
I can definitely see a use case for that. Thank you.

I have frozen features through 2022 for personal reasons (programming addiction is real!). But I will leave this one open and pick it up in 10 months. A contributor might come along between now and then. If not, it's definitely on the "roadmap" for 2023.

**Comment by dshefman1** [comment]
FYI: I found out that [pandas.read_html](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_html.html) implements exactly this behavior I requested in this feature request. The input is html containing a table and the output is a Pandas dataframe with the cells unmerged and duplicated. When you come back to this in 9 months, I thought you might be interested in reading the [documentation ](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_html.html)and the GitHub [code](https://github.com/pandas-dev/pandas).

**Comment by ShayHill** [comment]
## 2.5.0 (2023-01-23)

### Feat

- add argument duplicate_merged_cells for docx tables

```
    with docx2python(RESOURCES / "merged_cells.docx") as content:
        assert content.body[0] == [
            [["0-0"],  ["0-12"],   ["0-3"]],
            [["12-0"], ["1-1"],    ["1-2"],    ["1-3"]],
            [[""],     ["2-1"],    ["2-2"],    ["2-3"]],
            [["3-0"],  ["34-123"]],
            [["4-0"],  [""]],
        ]

    with docx2python(RESOURCES / "merged_cells.docx", duplicate_merged_cells=True) as content:
        assert content.body[0] == [
            [["0-0"],  ["0-12"],   ["0-12"],   ["0-3"]],
            [["12-0"], ["1-1"],    ["1-2"],    ["1-3"]],
            [["12-0"], ["2-1"],    ["2-2"],    ["2-3"]],
            [["3-0"],  ["34-123"], ["34-123"], ["34-123"]],
            [["4-0"],  ["34-123"], ["34-123"], ["34-123"]],
        ]
```
