### ISSUE TITLE
Math Equations is not properly rendered

### ISSUE THREAD

**Issue by adiptamartulandi** [ShayHill/docx2python#36]
hello i have found an issues. i have math equations like this
<img width="168" alt="image" src="https://user-images.githubusercontent.com/53418888/176585964-c870df7b-87ca-495e-b1d1-409d7609ebe7.png">

but the docx2python rendered that equation is like this
<img width="157" alt="image" src="https://user-images.githubusercontent.com/53418888/176586080-42c77727-ca4e-4ede-91ef-e7207d7ae6a3.png">

i think some symbol is missing like () and sum
here is example docs

[test.docx](https://github.com/ShayHill/docx2python/files/9016176/test.docx)

thanks!

**Comment by ShayHill** [comment]
Thank you for the report. Docx2Python does not support “Professional”-formatted equations. To export these, you’d have to change the format to “Linear” by hovering over the equation and clicking the downward arrow.

From: Adipta Martulandi ***@***.***>
Sent: Wednesday, June 29, 2022 10:25 PM
To: ShayHill/docx2python ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShayHill/docx2python] Math Equations is not properly rendered (Issue #36)


hello i have found an issues. i have math equations like this
[image]<https://user-images.githubusercontent.com/53418888/176585964-c870df7b-87ca-495e-b1d1-409d7609ebe7.png>

but the docx2python rendered that equation is like this
[image]<https://user-images.githubusercontent.com/53418888/176586080-42c77727-ca4e-4ede-91ef-e7207d7ae6a3.png>

i think some symbol is missing like () and sum
here is example docs

test.docx<https://github.com/ShayHill/docx2python/files/9016176/test.docx>

thanks!
