### ISSUE TITLE
Databricks command in Cancelled status post the latest library release

### ISSUE THREAD

**Issue by Initha-Bhaskaran** [ShayHill/docx2python#39]
Hi,
Post the latest docx2Python library on Jan-19, all the notebook command execution are in cancelled status. we tried to use the previous version number and still there were failures inconsistently. But once we removed the library from the cluster, all the notebook runs were successful. Can you look into the issue with latest library release?

**Comment by ShayHill** [comment]
Can you share some code showing what is happening? I am not sure what you mean by "notebook command execution".

**Comment by Initha-Bhaskaran** [comment]
Hi, It is basic dbutils command, when it tries to execute-just goes to cancelled status within a second. when we remove the library from the cluster the code works fine.

**Comment by ShayHill** [comment]
I do not have a database to test against. If you give me the specific error message, I *might* be able to assist you.
