### ISSUE TITLE
Html style info in not accurate

### ISSUE THREAD

**Issue by AtulUjjwal** [ShayHill/docx2python#40]
While reading a docx file with (html = True) in python, the information like Bold, Italics etc. are not all correct in the output.
Attaching snippets for the input(word file) and output(code) .

In this case the 2nd line is not captured as bold.(<b>)

<img width="434" alt="code" src="https://user-images.githubusercontent.com/13176536/215703758-0e2ad80c-3fbc-45d9-b0d9-b5e612878a3b.png">
<img width="266" alt="word file" src="https://user-images.githubusercontent.com/13176536/215703761-e422f1ef-992b-4cda-b269-c9b80894a4ec.png">

**Comment by ShayHill** [comment]
Thank you. Can you supply a document that is not reading correctly?

Sent from my iPhone

On Jan 31, 2023, at 02:15, Atul Ujjwal ***@***.***> wrote:

﻿

While reading a docx file with (html = True) in python, the information like Bold, Italics etc. are not all correct in the output.
Attaching snippets for the input(word file) and output(code)
[code]<https://user-images.githubusercontent.com/13176536/215703758-0e2ad80c-3fbc-45d9-b0d9-b5e612878a3b.png>
[word file]<https://user-images.githubusercontent.com/13176536/215703761-e422f1ef-992b-4cda-b269-c9b80894a4ec.png>
