### ISSUE TITLE
Add breakline when using replace_docx_text method

### ISSUE THREAD

**Issue by maiskovich** [ShayHill/docx2python#41]
Hello,

I am using the method `replace_docx_text`, and I found it very useful. I recently noticed that when my text to replace contains a break line this doesn't get applied to the resulting file (is just ignored); for example:
`  replace_docx_text(
    'source.docx',
    str(keys_values_dict[row]['file_name'])+'.docx',
    [('document_name', '\r\nTEST-ID123')],  
    html=True,
    )`
\r\n breakline before the string gets replaced in the final document as just the string (and \r\n is not creating a new line and not visible, the end result is just 'TEST-ID123')
I tried replacing \r\n by just \n, but the result was the same.

Is there an option I can use to insert this break line?

Thank you

**Comment by ShayHill** [comment]
Thank you. I will have a look this morning.

**Comment by ShayHill** [comment]
feat: preserve newlines in replace_docx_text

replace_docx_text now preserves newlines in the replacement text, so "some string" can be replaced with "some\\nstring". Newlines are written in the docx xml as <br> elements, not paragraphs. This is similar to the soft breaks inserted in MS Word when pressing <Shift-Enter>. Soft breaks will, as before, be exported as "\\n".

closes issue https://github.com/ShayHill/docx2python/issues/41 Add breakline when using replace_docx_text method

On pypi as version 2.6.3

**Comment by maiskovich** [comment]
great, thank you very much @ShayHill, that was really quick.
