### ISSUE TITLE
TypeError("will not iterate over sequence item") when using .text

### ISSUE THREAD

**Issue by peterfarrell** [ShayHill/docx2python#5]
In the current version on PyPi (1.21), we are getting `TypeError("will not iterate over sequence item")` when trying to get the text of a document.  We installed from the repo here and everything is ok. Would you push a new release to PyPi?

**Comment by ShayHill** [comment]
Hmmm. Should match. I will update in about ½ hour. Thank you for the report.

**Comment by ShayHill** [comment]
On pypi now as 1.22. Please confirm if this works for you.

-Shay

**Comment by peterfarrell** [comment]
@ShayHill  New version works great.

**Comment by ShayHill** [comment]
Great news! Thank you again.
