### ISSUE TITLE
Footnotes implementation

### ISSUE THREAD

**Issue by Salvodif** [ShayHill/docx2python#58]
Hi,
I wanted to use your library to extract all the citations I have in a text of mine in order to create a bibliography. This would then only be an experiment to create my own system.
Unfortunately, however, the library returns footnotes as a long string and not as a list of objects that I can then manipulate.
Would it be possible to think of a similar implementation?

**Comment by ShayHill** [comment]
Can you provide an example docx and an example of your desired output?

**Comment by Salvodif** [comment]
> Can you provide an example docx and an example of your desired output?
[Salvatore Di Fazio.docx](https://github.com/ShayHill/docx2python/files/15152252/Salvatore.Di.Fazio.docx)

this is a 8 pages of example.

my idea (perhaps because I come from the C# world) was to find docx_content.footnotes_runs as a list of footnotes, which would be nothing more than strings, so that I could manipulate them and extract author, title, etc. according to the regex I would apply to them

**Comment by ShayHill** [comment]
Unfortunately, Word does not differentiate author, date, etc. in footnotes. The runs are broken up almost arbitrarily. For instance, these would be the footnote runs in your document (extracted by running some editor macros on the xml).


```
 " Cf.", " ", "Benedetto XVI", ", ", "Discorso a", "ll’Assemblea Generale della Conferenza Episcopale Italiana", ", 27 maggio 2010", "."

" ", "Cf.", " ", "Francesco", ", ", "Messaggio per la LVII giornata mondiale della pace: Intelligenza artificiale e pace", ", 1° maggio 2024", "."

" Cf. ", "P. ", "Benanti", ", ", "Le Macchine sapienti: Intelligenze artificiali e decisioni umane", ", Marietti 1820, Bologna 2019", ", 92."

" Cf. ", "L. ", "Floridi", ", ", "La quarta rivoluzione: Come l’infosfera sta trasformando il mondo", ", Raffaello Cortina, Milano 2017", ", ", "99-100."

" Cf. ", "Ivi", ", 101."

" ", "B. ", "Mondin", ", ", "Dizionario Enciclopedico del pensiero di San Tommaso d’Aquino", ", ESD, Bologna 1991", ", 74-75."

" Cf. ", "E.J. ", "Hobsbawm", ", ", "La rivoluzione industriale e l’impero. Dal 1750 ai giorni nostri", ", Piccola Biblioteca Einaudi, Torino 1972", ", 29."

" Cf. ", "Ivi", ", 28."

" Cf. ", "Ivi", ", 34."

" Cf. ", "Ivi", ", 59."

" Cf. ", "Ivi", ", 54-55."

" Cf. ", "Ivi", ", 69."

" Cf. ", "Ivi", ", 117-119."

" Cf. ", "Ivi", ", 193-194."

" Cf. ", "Ivi", ", 196."

" Cf. ", "Ivi", ", 197."

" Cf. ", "Ivi", ", 234-235."

" Cf. ", "Ivi", ", 238."

" Cf. ", "P. ", "Benanti", ", ", "Le macchine sapienti", ", 52."

" ", "P. ", "Harpe", " – H. ", "Hegt", " – A. ", "van", " ", "Roermund", ", ", "Smart AD and DA Conversion", ", Springer Netherlands, Dordrecht 2012", ",", " 1."

" ", "H. ", "Lala", ", ", "Storia dell’ingegner Mario Tchou dell’Olivetti, che riuscì a battere sul tempo l’Ibm", ", ", "Wired Italia", ", ", "20 gennaio 2021", ", in https://www.wired.it/economia/business/2021/01/20/olivetti-mario-tchou-elea-ibm/ (Consultato: 6 aprile 2024)"

" ", "J. ", "Rifkin", ", ", "The Third Industrial Revolution: How Lateral Power Is Transforming Energy, the Economy, and the World", ", St. Martin’s Press 2011", ",", " 113."

" ", "Cf. ", "J. ", "Abbate", ", ", "Inventing the Internet", ", MIT Press, Massachusetts 1999", ",", " 140."
```

I'm afraid there is no way to accomplish what you want.

**Comment by Salvodif** [comment]
perhaps I have explained myself wrongly. I would make the distinction author, title, etc. with a regex.
The problem is that docx2python fills the variable docx_content.footnotes_runs with one string with all the footnotes. If it were a list of strings instead, you could use it to do this

**Comment by ShayHill** [comment]
The footnotes are returned as a (nested) list of individual strings. To flatten it:

```
from docx2python.iterators import iter_paragraphs
from docx2python import docx2python


with docx2python("Salvatore.Di.Fazio.docx") as output:
    footnotes = output.footnotes

individual_footnote_strings = list(iter_paragraphs(footnotes))
```
