### ISSUE TITLE
read value of field 

### ISSUE THREAD

**Issue by ardianfe** [ShayHill/docx2python#6]
I try to read Word file that includes the combo box and checkbox field, but when parsing it, the values are empty, but if it is text box the value is returned.  can this library read the type of this field?
thanks

**Comment by ShayHill** [comment]
Please send a sample docx file.

Sent via the Samsung Galaxy S9+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ardianfe** [comment]
Hi @ShayHill  this is a sample docx file.
[test.docx](https://github.com/ShayHill/docx2python/files/4784191/test.docx)

thank you

**Comment by ShayHill** [comment]
I’m having a look this morning. Looks straightforward to add this functionality. Will let you know more this afternoon.

Thank you.

**Comment by ShayHill** [comment]
On PyPi now. Version 1.24 should get the information from your checkboxes and dropdowns.

Checkboxes will appear in the output text as \u2610 (open checkbox glyph) or \u2612 (selected checkbox glyph). Let me know how it works out.

**Comment by ardianfe** [comment]
Great, I'm going to try, soon I let you know

**Comment by ardianfe** [comment]
Hi @ShayHill its work
thank you so much

**Comment by ShayHill** [comment]
My pleasure. If you have a chance, please star my project.

-Shay

**Comment by ardianfe** [comment]
I have stared your project first time I use it..

**Comment by ShayHill** [comment]
Thank you. I definitely appreciate it.


-------- Original message --------
