### ISSUE TITLE
KeyError: '{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id'

### ISSUE THREAD

**Issue by Link-Go** [ShayHill/docx2python#7]
how can i solve it

**Comment by ShayHill** [comment]
Thank you for the report. I need to have a look at the document you're working with.

**Comment by leboni** [comment]
Hi, I have this same issue when I try to read a file that has a Table of Contents, even the most simple file fails. Attached is the file I'm using to test it. In the moment I delete the table of contents the code works and is able to read the document.
[zen_of_python.docx](https://github.com/ShayHill/docx2python/files/5092328/zen_of_python.docx)

**Comment by ShayHill** [comment]
Thank you. I definitely want to support table of contents. I should have thought to test this from the beginning.

I will add this support.


-------- Original message --------

**Comment by ShayHill** [comment]
Version 1.25 is up. Docx2python will now extract TOC text. TOC internally is built like a list of hyperlinks with anchors (internal file links) instead of hrefs. Will ignore the internal links (meaningless outside the docx) and grab the TOC text.

Closing. Thank you.
