### ISSUE TITLE
Custom Document Number Formats

### ISSUE THREAD

**Issue by medha-hegde** [ShayHill/docx2python#75]
Hi,

I'm processing .docx files which contain "Document Number Formats":
<img width="395" alt="image" src="https://github.com/user-attachments/assets/0b1fbd30-f5d5-4dd8-8ca2-15c23befc59e">

On processing the file with this code, it shows up as a usual bulleted list with `--` or not a list at all:

Word doc:
<img width="475" alt="image" src="https://github.com/user-attachments/assets/e0f2b27a-179b-4624-b470-3dde6fd39a99">

Code output:
![image](https://github.com/user-attachments/assets/77109eeb-2fb1-4cc1-9993-bab531682c9c)

Is there a way to extract the custom Document Number Formatting?

**Comment by ShayHill** [comment]
I will have a look.

On Oct 3, 2024, at 11:24, medha hegde ***@***.***> wrote:

﻿

Hi,

I'm processing .docx files which contain "Document Number Formats":
image.png (view on web)<https://github.com/user-attachments/assets/0b1fbd30-f5d5-4dd8-8ca2-15c23befc59e>

On processing the file with this code, it shows up as a usual bulleted list with --:

Word doc:
image.png (view on web)<https://github.com/user-attachments/assets/e0f2b27a-179b-4624-b470-3dde6fd39a99>

Code output:
image.png (view on web)<https://github.com/user-attachments/assets/77109eeb-2fb1-4cc1-9993-bab531682c9c>

Is there a way to extract the custom Document Number Formatting?

**Comment by ShayHill** [comment]
Can you provide an example document?

**Comment by medha-hegde** [comment]
sure! 
[word2text.docx](https://github.com/user-attachments/files/17274956/word2text.docx)
