### ISSUE TITLE
Wanted to know whether adding multi-level headings and tables function in it 

### ISSUE THREAD

**Issue by a136214808** [ShayHill/docx2python#78]
It would be nice if we could recognise multi-level headings and tables.

**Comment by ShayHill** [comment]
In what way? Multi level heading and labels are recognized now. What specifically are you wanting to do?

On Nov 5, 2024, at 02:13, a136214808 ***@***.***> wrote:

﻿

It would be nice if we could recognise multi-level headings and tables.
