### ISSUE TITLE
Getting Tags of the Content Control Blocks

### ISSUE THREAD

**Issue by YashasviMantha** [ShayHill/docx2python#81]
Hi I have been trying to extract the text and metadata of Content Control blocks. And while I am able to extract the text inside of the box; I am not able to figure out how to extract the metadata (properties). 

For example, in this [ControlTest.docx](https://github.com/user-attachments/files/17744652/ControlTest.docx) document, I would like to extract the text along with the `Content Control Porperties` like Title, tag etc. In the attached document case it would be : `Test_Control`.

I am using the `document_pars()` to get the text. But it would be amazing if we can also get the tags. Is this possible in anyway right now?

**Comment by YashasviMantha** [comment]
Thanks @ShayHill ! Obviously, happy to contribute in anyway as well for this.

**Comment by ShayHill** [comment]
To facilitate this, I've added an `.elem` attribute to `Par` instances. This is a pointer to the xml element from which the `Par` instance was created. This should bridge the gap between stepping through the xml yourself (tricky given the docx file structure) and exposing properties one-by-one through `Par` and `Run` instances. The test file `test_content_control_block_properties.py` has an example for accessing the `tag` attribute value of a parent `sdt` element.

```
from lxml.etree import _Element as EtreeElement  # type: ignore

from docx2python.attribute_register import Tags
from docx2python.iterators import iter_paragraphs
from docx2python.main import docx2python
from docx2python.text_runs import gather_Pr
from tests.conftest import RESOURCES

_DOCX = RESOURCES / "ControlTest.docx"


def get_sdt_tag(elem: EtreeElement) -> str | None:
    """If elem is or is inside a <w:sdt> element, try to find the sdt props tag value.

    :param elem: lxml.etree._Element object
    :return: tag value of sibling or parent sdtPr element or None

    <w:body>
        <w:sdt>
            <w:sdtPr>
                <w:tag w:val="my_tag"/>
            </w:sdtPr>
            <w:sdtContent>
                <w:p> </w:p>
                <w:p> </w:p>
            </w:sdtContent>
        </w:sdt>
    </w:body>

    """
    properties_dict = gather_Pr(elem, Tags.SDT)
    return properties_dict.get("tag")


class TestStructuredDocumentTags:

    def test_paragraphs_in_sdt_elements(self) -> None:
        """Get the SDT tag above a paragraph."""
        with docx2python(_DOCX) as extraction:
            pars = extraction.document_pars

        text_paragraphs: list[str] = []

        for paragraph in iter_paragraphs(pars):
            if paragraph.elem is None:
                par_tag = None
            else:
                par_tag = get_sdt_tag(paragraph.elem)
            par_text = "".join(paragraph.run_strings)
            text_paragraphs.append(f"[{par_tag}]: {par_text}")

        assert text_paragraphs == [
            "[Test_Control]: This is a test",
            "[Test_Control]: For a content control or content container in word. ",
        ]
```

**Comment by YashasviMantha** [comment]
Thanks @ShayHill, I did test the latest push on some complex word documents. And even the nesting works as expected. Cheers!

**Comment by ShayHill** [comment]
Great to hear it.

On Nov 18, 2024, at 07:52, Yashasvi Mantha ***@***.***> wrote:

﻿

Thanks @ShayHill<https://github.com/ShayHill>, I did test the latest push on some complex word documents. And even the nesting works as expected. Cheers!
