### ISSUE TITLE
Can it read from stream bytes data ?

### ISSUE THREAD

**Issue by multinucliated** [ShayHill/docx2python#9]
I was looking in the documentation , I didn't get get any example for extracting the text from stream file object .

For eg :

`
from docx2python import docx2python
text = docx2python(file_obj.read())
print(text)
`

**Comment by ShayHill** [comment]
Thank you for your interest.

Docx2python should work for your case without the .read()

text=docx2python(file_obj).text

Docx2python access content with

zipf = zipfile.ZipFile(argument)

Where 'argument' can be a file name or file object. So, docx2python can read anything zipfile can read. I will incorporate this into the document next update.

**Comment by multinucliated** [comment]
Actually , that file object will be coming from Flask request object , ie "file storage type" object . will that work in that case ?

**Comment by ShayHill** [comment]
I am not sure and have no straightforward way to test. If you are successful, please let me know.

________________________________

**Comment by multinucliated** [comment]
Yes I'm trying and trying to make my own logic for that . 
I'm getting one issue of zipping the docx file , once its completed I'll be done with this problem !

**Comment by ShayHill** [comment]
Awesome. Let me know how it goes and if I can help.

**Comment by multinucliated** [comment]
https://gist.github.com/etienned/7539105#file-extractdocx-py

http://etienned.github.io/posts/extract-text-from-word-docx-simply/

Check this out ! I think I got the answer for my query ! also you can import this to your module !

**Comment by ShayHill** [comment]
Thank you very much for the report!

Docx2python should work the same way. I’d like to run some tests to see / adjust. Can you advise the most straightforward way for me to generate a Flask object from a local docx file?

**Comment by multinucliated** [comment]
I didn't get it properly , Shall I make you 2small API in a flask where you can text the both ? (with stream and without stream ) ?

Let me know , how shall I provide you the code ?

**Comment by ShayHill** [comment]
Sorry for the slow reply. I've been out of pocket.

The API would be great!

If it's easy for you, you could send the code directly to my e-mail. shay_public@hotmail.com

________________________________

**Comment by multinucliated** [comment]
No issues! Let me build that on this weekend, I'll definitely share it to you !

**Comment by ShayHill** [comment]
Awesome! Thank you.

________________________________

**Comment by multinucliated** [comment]
Sorry , I'm running late for my rest of the deadlines , I'll be sending you on next weekend . Please stay tune !

**Comment by ShayHill** [comment]
Appreciate the help anytime. Thank you, Anshul.


-------- Original message --------
